#!/usr/bin/env sh
# This file is automatically added by husky
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# WARNING: DO NOT EDIT THIS FILE.                          #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# This file is automatically added by husky.
# If you see this in your commit, it means that
# 1. You're using an old version of husky
# 2. You didn't install husky correctly
# The solution is to:
# 1. Remove the old husky installation
#    - Remove .git/hooks/pre-commit (if it exists)
#    - Remove .husky/* (if it exists)
# 2. Run: npm install husky --save-dev
# 3. Run: npx husky install
# Or run: npx husky-init and follow the instructions

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

# Git 2.13 and above support --no-display and --no-pager
if command_exists git && [ -z "${GIT_NO_DISPLAY+set}" ]; then
  export GIT_NO_DISPLAY=1
fi

# Hooks can fail for many reasons, let's try to understand why
if [ -z "${HUSKY+set}" ]; then
  case "$(uname -s 2>/dev/null)" in
    Linux*)     HUSKY=linux   ;;
    Darwin*)    HUSKY=macos   ;;
    CYGWIN*|MINGW*|MSYS*) HUSKY=windows ;;
    *)          HUSKY=unknown  ;;
  esac
  
  # If CI is set, we're in a CI environment
  if [ -n "${CI+set}" ]; then
    HUSKY=ci
  fi
  
  # Check if we're in a pty (pseudo-terminal)
  if [ -t 1 ] && [ -z "${HUSKY_PTY+set}" ]; then
    HUSKY=pty
  fi
  
  export HUSKY
fi

# Try to run the command, if it fails, try with bun
if command_exists node; then
  NODE=node
elif command_exists bun; then
  NODE=bun
else
  echo "Husky: Cannot find node or bun, skipping hook"
  exit 0
fi

# Run the hook script
$NODE --no-warnings --loader ts-node/esm "$@"
